# Main Engine Simulation Configuration

modbus:
  host: "0.0.0.0"    # WARNING: This makes the server accessible from any IP
  port: 502          # Standard Modbus TCP port

engine:
  # RPM ranges
  rpm_min: 600
  rpm_max: 1200
  rpm_normal: 900
  
  # Temperature ranges (°C)
  temp_min: 70
  temp_max: 120
  temp_normal: 85
  
  # Fuel flow ranges (tons/hour)
  fuel_flow_min: 0.5
  fuel_flow_max: 2.5
  fuel_flow_normal: 1.5

  # Update interval (seconds)
  update_interval: 1.0

# WARNING: These registers are publicly accessible without authentication
registers:
  status: 0          # 0: Stopped, 1: Running, 2: Warning, 3: Alarm
  rpm: 1
  temp: 2
  fuel_flow: 3
  load: 4 