# Main Engine Simulation Configuration

modbus:
  host: "localhost"   # Explicitly use localhost
  port: 5020         # Using non-privileged port

engine:
  # RPM ranges
  rpm_min: 600
  rpm_max: 1200
  rpm_normal: 900
  
  # Temperature ranges (°C)
  temp_min: 70
  temp_max: 120
  temp_normal: 85
  
  # Fuel flow ranges (tons/hour)
  fuel_flow_min: 0.5
  fuel_flow_max: 2.5
  fuel_flow_normal: 1.5

  # Update interval (seconds)
  update_interval: 1.0

# Modbus register mapping (using standard Modbus addresses)
registers:
  rpm: 40001        # Engine RPM
  temp: 40002       # Engine Temperature
  fuel_flow: 40003  # Fuel Flow Rate
  load: 40004       # Engine Load
  status: 40005     # Engine Status (0: Stopped, 1: Running, 2: Warning, 3: Alarm) 