version: '3.8'

services:
  modbus-engine:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: engine-simulator-modbus
    ports:
      - "502:502"    # MODBUS TCP port
      - "5020:502"   # Alternative port for non-root access
    environment:
      - MODBUS_HOST=0.0.0.0
      - MODBUS_PORT=502
      - PYTHONUNBUFFERED=1
    volumes:
      - ./config_linux.yaml:/app/config.yaml:ro
      - ./logs:/app/logs
    restart: unless-stopped
    
    # Security options
    security_opt:
      - no-new-privileges:true
    read_only: false
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s=socket.socket(); s.settimeout(5); s.connect(('localhost', 502)); s.close()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: engine-network 